# Generated by Django 3.2 on 2021-12-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=400)),
                ('no_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
